/** Brazilian Portuguese additions for the upstream locale namespaces. */

export const PT_BR: Record<string, Record<string, string>> = {
  common: {
    cancel: 'Cancelar',
    close: 'Fechar',
    save: 'Salvar',
    retry: 'Tentar novamente',
    loading: 'Carregando…',
    delete: 'Excluir',
    edit: 'Editar',
    remove: 'Remover',
    confirm: 'Confirmar',
  },
  settings: {
    trigger: 'Configurações',
    title: 'Configurações',
    close: 'Fechar',
    openDocument: 'Abrir arquivo de configuração',
    'openDocument.error': 'Não foi possível abrir o arquivo de configuração',
    'general.nav': 'Geral',
    'connection.error': 'Desconectado',
    'connection.retry': 'Reconectar agora',
    'connection.connecting': 'Reconectando',
    'connection.connected': 'Conectado',
    'connection.reconnect': 'Desconectado. Reconectar agora',
    'connection.restart': 'Reconectando automaticamente. Reconectar agora',
  },
  'settings.theme': {
    'appearance.title': 'Aparência',
    'appearance.light': 'Claro',
    'appearance.dark': 'Escuro',
    'appearance.system': 'Seguir o sistema',
    'fontSize.title': 'Tamanho da fonte',
    'fontSize.description': 'Afeta apenas o conteúdo das conversas',
    'fontSize.unit': 'px',
    'fontSize.increase': 'Aumentar tamanho da fonte',
    'fontSize.decrease': 'Diminuir tamanho da fonte',
  },
  'settings.permission': {
    title: 'Permissões',
    description: 'Escolha o modo de permissão padrão para novas sessões',
    loading: 'Carregando',
    unavailable: 'Indisponível',
    'preset.readOnly': 'Somente leitura',
    'preset.workspaceWrite': 'Gravar no workspace',
    'preset.fullAccess': 'Acesso total',
    'confirm.title': 'Ativar acesso total?',
    'confirm.description': 'O acesso total reduz confirmações e permite mais ações diretas, incluindo operações sensíveis, alterações de arquivos e comandos externos. Use apenas quando confiar nas tarefas seguintes.',
    'confirm.acknowledge': 'Entendo os riscos e quero continuar',
    'confirm.cancel': 'Cancelar',
    'confirm.enable': 'Ativar acesso total',
  },
  'permission.access': {
    'preset.readOnly': 'Somente leitura',
    'preset.workspaceWrite': 'Gravar no workspace',
    'preset.fullAccess': 'Acesso total',
    'confirm.title': 'Ativar acesso total?',
    'confirm.description': 'O acesso total reduz confirmações e permite mais ações diretas, incluindo operações sensíveis, alterações de arquivos e comandos externos. Use apenas quando confiar nas tarefas seguintes.',
    'confirm.acknowledge': 'Entendo os riscos e quero continuar',
    'confirm.cancel': 'Cancelar',
    'confirm.enable': 'Ativar acesso total',
  },
  'settings.models': {
    nav: 'Modelos',
    title: 'Modelos',
    intro: 'Informe suas chaves de API para usar modelos dos provedores abaixo.',
    edit: 'Editar',
    editProvider: 'Editar {provider}',
    remove: 'Excluir',
    removeProvider: 'Excluir {provider}',
    deleteTitle: 'Excluir {provider}?',
    deleteDescription: 'Excluir {provider} remove sua configuração. A credencial usada é gerenciada separadamente e será mantida.',
    deleteDescriptionWithCredential: 'Excluir {provider} remove sua configuração e a chave de API armazenada.',
    deleteConfirm: 'Excluir {provider}',
    deleting: 'Excluindo {provider}…',
    add: 'Adicionar provedor',
    provider: 'Provedor',
    close: 'Fechar',
    cancel: 'Cancelar',
    apply: 'Aplicar',
    applying: 'Aplicando…',
    savedProvider: '{provider} salvo.',
    credentialConfigured: 'Chave de API configurada',
    credentialMissing: 'Chave de API ausente',
    readOnly: 'O documento de configurações é somente leitura nesta instalação.',
    loadFailed: 'Falha ao carregar o catálogo de provedores',
    conflict: 'As configurações foram alteradas em outro local. Feche e reabra para editar os valores atuais.',
    retry: 'Tentar novamente',
    keyInput: 'Chave de API',
    keyPlaceholder: 'Informe sua chave de API',
    keyPlaceholderNative: 'Informe uma chave ou deixe vazio para usar a autenticação do ambiente',
    keyStored: 'Configurada. Informe um novo valor para substituir',
    keyEnvLocked: 'Fornecida pelo ambiente de inicialização (somente leitura)',
    customized: 'Configurações personalizadas',
    baseUrl: 'URL base',
    baseUrlDefault: 'Padrão do provedor',
    models: 'Modelos',
    modelsInherited: 'Usando os padrões do adaptador',
    modelsCustomized: 'Catálogo de modelos personalizado',
    resetModels: 'Restaurar padrões',
    model: 'Modelo',
    modelId: 'ID do modelo',
    modelName: 'Nome de exibição',
    modelNamePlaceholder: 'Usa o ID quando vazio',
    contextWindow: 'Janela de contexto',
    contextWindowPlaceholder: 'Usa o padrão do provedor',
    maxTokens: 'Máximo de tokens de saída',
    maxTokensPlaceholder: 'Usa o padrão do provedor',
    modelAdvanced: 'Capacidades',
    addModel: 'Adicionar modelo',
    removeModel: 'Excluir modelo',
    modelsEmpty: 'Nenhum modelo aparecerá no seletor. IDs não listados ainda podem ser enviados diretamente.',
    keyBlank: 'Informe a chave de API ou deixe vazio para manter a armazenada.',
    keyBlankNew: 'Informe a chave de API ou deixe vazio se este provedor usar outra autenticação.',
    keyIllegalCharacters: 'Esta chave de API não está em um formato válido.',
    modelIdRequired: 'O ID do modelo é obrigatório.',
    modelIdDuplicate: 'O ID do modelo deve ser exclusivo.',
    modelNameInvalid: 'O nome de exibição não pode ficar vazio.',
    modelContextInvalid: 'A janela de contexto deve ser uma quantidade positiva, como 131072, 256K ou 1M.',
    modelMaxTokensInvalid: 'O máximo de tokens deve ser uma quantidade positiva, como 8192, 64K ou 1M.',
    advancedHint: 'Outros campos ficam em settings.yaml; edite essa seção diretamente.',
    modelCapacityInvalid: 'A capacidade deve ser um número, opcionalmente com sufixo K ou M.',
    modelDuplicate: 'Cada ID de modelo pode aparecer apenas uma vez.',
    modelContextWindow: 'Janela de contexto',
    modelMaxTokens: 'Máximo de tokens de saída',
    keyRequired: 'Informe uma chave de API para continuar.',
    fetchModels: 'Buscar modelos disponíveis',
    fetching: 'Consultando o provedor…',
    fetchNeedsBaseUrl: 'Informe primeiro a URL base e faça a busca.',
    fetchEmpty: 'O provedor não listou modelos. Adicione-os manualmente.',
    fetchTitle: 'Escolha modelos para adicionar',
    fetchDescription: 'Estes são os modelos disponíveis neste provedor. Escolha os que deseja adicionar.',
    fetchSearch: 'Pesquisar modelos',
    fetchNoMatches: 'Nenhum modelo correspondente.',
    fetchSelectAll: 'Selecionar todos',
    fetchDeselectAll: 'Desmarcar todos',
    fetchAdopt: 'Adicionar selecionados',
    customAdd: 'Adicionar provedor personalizado',
    customTitle: 'Provedor personalizado',
    customTag: 'Personalizado',
    customRoute: 'ID do provedor',
    customRouteHint: 'Identificador minúsculo iniciado por letra, exclusivo nas solicitações e no nome da credencial.',
    customRouteInvalid: 'Comece com uma letra minúscula; depois use letras minúsculas, números e hífens.',
    customRouteTaken: 'Já existe um provedor com este ID.',
    customDisplayName: 'Nome de exibição',
    customApi: 'Protocolo da API',
    customApiUnset: 'Não selecionado',
    customNeedsBaseUrl: 'Um provedor personalizado precisa de uma URL base.',
    customBaseUrlInvalid: 'Informe uma URL HTTP ou HTTPS válida.',
    customNeedsModels: 'Um provedor personalizado precisa de pelo menos um modelo.',
    create: 'Criar provedor',
    creating: 'Criando…',
    onboardingTitle: 'Adicione uma chave de API para começar',
    onboardingDescription: 'Configure o provedor oficial DeepSeek para começar.',
    onboardingLater: 'Configurar depois',
    onboardingSave: 'Salvar e continuar',
    onboardingSaving: 'Salvando…',
  },
  'settings.plugins': {
    nav: 'Plugins',
    title: 'Plugins',
    intro: 'Configure e consulte os plugins instalados nesta instalação.',
    tabs: 'Visões de plugins',
    configurableTab: 'Configuração de plugins',
    empty: 'Esta instalação não expõe configurações de plugins.',
    overridden: 'Substituído',
    reset: 'Restaurar padrão',
    readOnly: 'As configurações desta instalação são somente leitura.',
    expand: 'Mostrar configurações',
    collapse: 'Ocultar configurações',
    save: 'Salvar',
    saving: 'Salvando…',
    discard: 'Descartar',
    unsaved: 'Não salvo',
    saveFailed: 'A instalação não aceitou estes valores; corrija-os.',
    invalidNumber: 'Informe um número ou deixe vazio para usar o padrão.',
    bashTitle: 'Shell',
    bashDescription: 'Limita cada comando executado pelo agente.',
    bashTimeoutMs: 'Tempo limite do comando (ms)',
    bashTimeoutMsHint: 'Por quanto tempo um comando pode executar antes de ser encerrado.',
    bashMaxOutputBytes: 'Limite de saída por fluxo (bytes)',
    bashMaxOutputBytesHint: 'O excedente é salvo em um arquivo temporário.',
    agentLoopTitle: 'Loop do agente',
    agentLoopDescription: 'Como o agente distribui chamadas de ferramentas.',
    agentLoopMaxParallel: 'Chamadas paralelas de ferramentas',
    agentLoopMaxParallelHint: 'Limite de chamadas seguras em paralelo dentro de uma etapa.',
    webSearchTitle: 'Pesquisa na web',
    webSearchDescription: 'Provedor de pesquisa DeepSeek.',
    webSearchApiKey: 'Chave de API',
    webSearchApiKeyHint: 'Armazenada fora do arquivo de configurações. Deixe vazio para manter a atual.',
    webSearchApiKeySet: 'Há uma chave configurada.',
    webSearchApiKeyUnset: 'Nenhuma chave configurada; a pesquisa está indisponível.',
    webSearchBaseUrl: 'Endpoint',
    webSearchBaseUrlHint: 'Deixe vazio para usar o padrão do provedor.',
    webSearchMaxUses: 'Máximo de pesquisas por solicitação',
    webSearchMaxUsesHint: 'Quantas vezes uma solicitação pode pesquisar antes de responder.',
    subagentModelSelectionTitle: 'Subagente',
    subagentModelSelectionDescription: 'Controle quais modelos os agentes podem escolher para subagentes.',
    subagentModelSelectionToggle: 'Permitir que agentes escolham modelos para subagentes',
    subagentModelSelectionAllowed: 'Modelos que os agentes podem escolher',
    subagentModelSelectionChoose: 'Quando ativado, agentes podem escolher provedor, modelo e esforço de raciocínio para cada subagente entre os modelos autorizados. Aplica-se apenas a novas sessões.',
    subagentModelSelectionLoading: 'Carregando modelos…',
    subagentModelSelectionLoadFailed: 'Não foi possível carregar os modelos.',
    subagentModelSelectionRetry: 'Tentar novamente',
    subagentModelSelectionUnavailable: 'Indisponível no momento',
    subagentModelSelectionUnavailableGroup: 'Salvo, mas indisponível no momento',
    subagentModelSelectionEmpty: 'Nenhum provedor anunciou um modelo.',
    subagentModelSelectionRequired: 'Selecione pelo menos um modelo antes de salvar.',
    subagentModelSelectionConflict: 'As configurações mudaram em outro local. Descarte o rascunho e tente novamente.',
    subagentModelSelectionOff: 'Subagentes usam os padrões configurados ou herdam o modelo do agente pai. As escolhas salvas são mantidas.',
  },
  'settings.agentPreset': {
    error: 'Não foi possível carregar as predefinições de agente.',
    userTrust: 'Personalizado',
    seatHint: 'Predefinição do agente para a sessão que será iniciada',
    headerHint: 'Predefinição usada por esta sessão, fixada no início',
    nav: 'Predefinições de agente',
    sectionIntro: 'Uma predefinição define os plugins, prompts e capacidades do agente de uma sessão. Duplique uma existente ou deixe o modo Criador preparar uma para você.',
    builtIn: 'Integrada',
    setDefault: 'Definir como padrão',
    view: 'Visualizar',
    presetStandardName: 'Modo padrão',
    presetStandardDescription: 'Agente de programação completo com edição de arquivos, shell, pesquisa, skills, planos, objetivos, subagentes e workflows.',
    presetPtcName: 'Modo PTC',
    presetPtcDescription: 'Agente completo sem a ferramenta workflow; as demais ferramentas são expostas pelo SDK PTC.',
    presetMinimalName: 'Modo mínimo',
    presetMinimalDescription: 'Agente de programação com uma ferramenta e shell persistente.',
    presetCordisName: 'Modo Criador',
    presetCordisDescription: 'Para criar predefinições personalizadas, com recursos do modo padrão e inspeção em tempo de execução.',
    duplicate: 'Duplicar',
    duplicateUnavailable: 'Esta instalação não possui um diretório de predefinições gravável',
    delete: 'Excluir',
    presetId: 'Identificador',
    presetIdPlaceholder: 'meu-agente',
    displayName: 'Nome',
    displayNamePlaceholder: 'Exibido no seletor; usa o identificador por padrão',
    inUse: 'Em uso',
    builtInGroup: 'Integradas',
    customGroup: 'Personalizadas',
    noDescription: 'Sem descrição.',
    brokenBadge: 'Falha ao carregar',
    brokenNoCopy: 'Uma predefinição com falha não pode ser duplicada',
    switchRefused: 'Não foi possível mudar para {name}: {reason}',
    copyOf: 'Copiada de',
    composition: 'Composição (agent.cordis.yml)',
    cancel: 'Cancelar',
    close: 'Fechar',
    retry: 'Tentar novamente',
    copyTitle: 'Duplicar predefinição',
    copyIntro: 'A predefinição inteira será copiada nesta máquina. O identificador se tornará o nome do diretório e não poderá ser alterado depois.',
    create: 'Criar',
    creating: 'Criando…',
    creatorDraft: 'Criar uma predefinição personalizada com o modo Criador',
    openLocation: 'Abrir pasta',
    showLocation: 'Mostrar localização',
    revealedPathLabel: 'Arquivos da predefinição:',
    idRequired: 'Informe um identificador para a predefinição.',
    idInvalid: 'Use letras minúsculas, números e hífens, começando por letra ou número.',
    idTaken: 'Já existe uma predefinição com este identificador.',
    deleteTitle: 'Excluir esta predefinição?',
    deleteDescription: 'O diretório da predefinição será excluído. Sessões em execução continuarão funcionando; novas sessões não poderão selecioná-la.',
    deleteConfirm: 'Excluir',
    deleting: 'Excluindo…',
  },
  'slash.menu': {
    command: 'Comandos',
    skill: 'Skills',
    subagent: 'Subagentes',
    loading: 'Carregando…',
    'drill.aria': 'Navegar pela pasta',
    'drill.hint': 'Navegar pela pasta',
    'drill.key': 'Tab',
    'crumbs.aria': 'Navegação de pastas',
    'suggestions.aria': 'Acionar sugestões',
  },
  chat: {
    'settings.transcript.title': 'Exibição da conversa',
    'settings.transcript.description': 'Controla o conteúdo de processo nas etapas concluídas',
    'settings.transcript.normal': 'Normal',
    'settings.transcript.compact': 'Compacta',
  },
  sidebar: {
    'session.new': 'Nova sessão',
    'session.new.label': 'Nova sessão',
    'toggle.open': 'Abrir barra lateral',
    'toggle.collapse': 'Recolher barra lateral',
    'panels.label': 'Painéis globais',
  },
  conversation: {
    'hint.plan': 'Descreva sua tarefa para gerar um plano',
    'hint.goal': 'Digite um objetivo para o agente executar continuamente',
    'hint.goal.active': 'Objetivo em andamento. Digite editar, pausar, continuar ou limpar',
    'placeholder.plan': 'Descreva sua tarefa para gerar um plano',
    'placeholder.default': 'Envie uma mensagem, use / para comandos ou @ para arquivos e conversas',
    'placeholder.unavailable': 'Sessão indisponível',
    'placeholder.parentOffline': 'A sessão principal está offline; não é possível enviar, mas você pode parar a execução atual',
    'placeholder.hero': 'Descreva o que você quer criar, use / para comandos ou @ para arquivos e conversas',
    'placeholder.workspace': 'Selecione um workspace para começar',
    'placeholder.steerQueue': 'Ctrl/Cmd+Enter envia todas as mensagens na fila',
    'input.commands': 'Comandos',
    'input.stop': 'Parar geração',
    'input.send': 'Enviar mensagem',
    'input.send.queue': 'Enviar para a fila',
    'input.send.steer': 'Enviar como intervenção',
    'input.accessMode': 'Modo de acesso atual: {name}',
    'attachment.pending': 'Anexo aguardando envio',
    'attachment.scrollLeft': 'Rolar anexos para a esquerda',
    'attachment.scrollRight': 'Rolar anexos para a direita',
    'attachment.dropTitle': 'Solte arquivos ou imagens aqui para adicioná-los',
    'attachment.dropDesc': 'Imagens: no máximo {count}, com {size} cada',
    'attachment.dropBlocked': 'Não é possível adicionar arquivos ou imagens agora',
    'image.pending': 'Imagem aguardando envio',
    'image.openOriginal': 'Abrir imagem original',
    'image.openOriginalLabel': '{label}. Clique para abrir a imagem original',
    'image.remove': 'Remover imagem',
    'image.original': 'Original',
    'image.label': 'Imagem',
    'image.loadFailed': 'Não foi possível carregar a imagem',
    'image.loading': 'Carregando imagem',
    'image.preview': 'Pré-visualização da imagem',
    'image.closePreview': 'Fechar pré-visualização da imagem',
    'image.unsupportedType': 'Tipo de imagem não compatível',
    'image.tooMany': 'Número máximo de imagens excedido',
    'image.fileTooLarge': 'A imagem é grande demais',
    'image.totalTooLarge': 'O tamanho total das imagens é grande demais',
    'image.tooManyPixels': 'A imagem tem pixels demais',
    'image.dimensionTooLarge': 'As dimensões da imagem são grandes demais',
    'image.modelUnsupported': 'O modelo atual não aceita imagens',
    'image.sendFailed': 'Falha ao enviar a imagem',
    'file.attach': 'Anexar arquivo',
    'file.pending': 'Arquivo aguardando envio',
    'file.remove': 'Remover arquivo',
    'file.uploading': 'Enviando arquivo',
    'file.uploadFailed': 'Falha ao enviar o arquivo',
    'file.retry': 'Tentar novamente',
    'file.stillUploading': 'O arquivo ainda está sendo enviado',
    'file.sessionUnavailable': 'Sessão indisponível para envio',
    'file.notStaged': 'Arquivo não preparado para envio',
    'file.label': 'Arquivo',
    'context.aria': 'Uso do contexto',
    'context.used': 'Contexto usado: {used}',
    'context.system': 'Sistema',
    'context.tools': 'Ferramentas',
    'context.messages': 'Mensagens',
    'settings.enter.title': 'Comportamento ao enviar durante a execução',
    'settings.enter.description': 'Define o que Enter e o botão Enviar fazem enquanto o agente está executando; Ctrl/Cmd+Enter usa o outro comportamento',
    'settings.enter.queue': 'Enviar para a fila',
    'settings.enter.steer': 'Enviar como intervenção',
    'access.preset.readOnly': 'Somente leitura',
    'access.preset.workspaceWrite': 'Gravar no workspace',
    'access.preset.fullAccess': 'Acesso total',
    'access.confirm.title': 'Confirmar modo de acesso',
    'access.confirm.description': 'Este modo permite que o agente execute ações adicionais. Deseja continuar?',
    'access.confirm.acknowledge': 'Entendi',
    'access.confirm.cancel': 'Cancelar',
    'access.confirm.enable': 'Ativar',
    'hero.headline': 'O que você quer criar?',
    'hero.preview': 'Pré-visualização',
    'hero.chooseWorkspace': 'Escolher workspace',
    'session.hierarchy': 'Hierarquia da sessão',
    'todo.title': 'Tarefas',
    'todo.progress.done': 'Concluídas',
    'todo.progress.active': 'Em andamento',
    'todo.progress.pending': 'Pendentes',
    'todo.rowTitle': 'Tarefa',
    'todo.completed': 'Concluída',
    'command.attachmentsUnsupported': 'Anexos não são compatíveis com este comando',
    'ask.rowTitle': 'Pergunta',
    'ask.waiting': 'Aguardando resposta',
    'ask.cancelled': 'Pergunta cancelada',
    'ask.cancelledDetail': 'A pergunta foi cancelada',
    'ask.interrupted': 'Pergunta interrompida',
    'ask.interruptedDetail': 'A pergunta foi interrompida',
    'ask.answered': 'Respondida',
    'ask.skipped': 'Ignorada',
    'bash.running': 'Executando comando',
    'bash.failed': 'Falha ao executar comando',
    'bash.stopped': 'Comando interrompido',
    'row.running': 'Em execução',
    'row.failed': 'Falhou',
    'row.stopped': 'Interrompido',
    'row.input': 'Entrada',
    'row.output': 'Saída',
    'row.inspect': 'Inspecionar',
    'tool.title.search': 'Pesquisar',
    'tool.title.read': 'Ler arquivo',
    'tool.title.bash': 'Executar comando',
    'tool.title.write': 'Escrever arquivo',
    'tool.title.edit': 'Editar arquivo',
    'tool.title.code': 'Executar código',
    'tool.title.generic': 'Ferramenta',
    'tool.title.inspect': 'Inspecionar',
    'tool.title.runCordis': 'Executar Cordis',
    'tool.title.stopCordis': 'Parar Cordis',
    'tool.title.removeCordis': 'Remover Cordis',
    'tool.title.pwsh': 'Executar PowerShell',
    'tool.title.readImage': 'Ler imagem',
    'tool.title.grep': 'Pesquisar no conteúdo',
    'tool.title.glob': 'Localizar arquivos',
    'tool.title.webSearch': 'Pesquisar na web',
    'tool.title.webFetch': 'Consultar página',
    'diff.files.one': '{count} arquivo',
    'diff.files.other': '{count} arquivos',
    'diff.collapseAria': 'Recolher diferenças',
    'diff.expandAria': 'Expandir diferenças',
    'diff.expandRest': 'Expandir restante',
    'read.window': 'Janela de leitura',
    'read.collapseAria': 'Recolher leitura',
    'read.expandAria': 'Expandir leitura',
    'read.expandRest': 'Expandir restante',
    'search.paths': 'Caminhos encontrados',
    'search.paths.truncated': 'Caminhos encontrados (lista truncada)',
    'search.matches': 'Correspondências',
    'search.matches.truncated': 'Correspondências (lista truncada)',
    'search.noResults': 'Nenhum resultado encontrado',
    'search.collapseAria': 'Recolher resultados',
    'search.expandAria': 'Expandir resultados',
    'search.expandRest': 'Expandir restante',
    'web.noResults': 'Nenhum resultado encontrado',
    'web.sourcesTruncated': 'Fontes restantes ocultas',
    'web.http': 'Resposta HTTP',
    'web.contentTruncated': 'Conteúdo truncado',
    'details.running': 'Em execução',
    'queue.count': '{count} na fila',
    'queue.sending': 'Enviando',
    'queue.image': 'Imagem',
    'queue.file': 'Arquivo',
    'queue.edit': 'Editar',
    'queue.edit.unsupported': 'Este item não pode ser editado',
    'queue.save': 'Salvar',
    'queue.cancelEdit': 'Cancelar edição',
    'queue.remove': 'Remover da fila',
    'queue.steer': 'Enviar agora',
    'queue.steer.unavailable': 'Não é possível enviar agora',
    'queue.editFailed': 'Falha ao editar item da fila',
    'queue.removeFailed': 'Falha ao remover item da fila',
    'queue.steerFailed': 'Falha ao enviar item da fila',
    'terminal.signal': 'Sinal: {signal}',
    'terminal.exitCode': 'Código de saída: {code}',
    'terminal.running': 'Terminal em execução',
    'terminal.failed': 'Falha no terminal',
    'terminal.done': 'Terminal concluído',
    'terminal.noOutput': 'Sem saída',
    'terminal.collapseAria': 'Recolher terminal',
    'terminal.expandAria': 'Expandir terminal',
    'terminal.expandRest': 'Expandir restante',
    'terminal.sendInput': 'Enviar entrada ao terminal',
    'terminal.session': 'Sessão do terminal',
  },
}
